### ISSUE TITLE
Timing issues when running demo inside VMWare VM

### ISSUE THREAD

**Issue by Symmetric** [Metaswitch/calico-docker#2]
I'm trying to run the demo on my dev box, which is a VMWare VM. The setup scripts took a very long time, though I did eventually get to the "Creating networked endpoints" step.

At that point, I didn't get connectivity between the containers, and there were some errors in the master logs:

```
2015-01-23 00:55:31,183 [ERROR] __main__ 335: Terminating on exception
Traceback (most recent call last):
  File "plugin.py", line 333, in <module>
    main()
  File "plugin.py", line 327, in main
    do_ep_api()
  File "plugin.py", line 172, in do_ep_api
    send_all_eps(create_sockets, host, resync_id)
  File "plugin.py", line 223, in send_all_eps
    create_socket.recv()
  File "socket.pyx", line 622, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5560)
  File "socket.pyx", line 656, in zmq.backend.cython.socket.Socket.recv (zmq/backend/cython/socket.c:5380)
  File "socket.pyx", line 139, in zmq.backend.cython.socket._recv_copy (zmq/backend/cython/socket.c:1758)
  File "checkrc.pxd", line 15, in zmq.backend.cython.checkrc._check_rc (zmq/backend/cython/socket.c:5960)
Again: Resource temporarily unavailable
```

Here  are the links to the diags bundles:

[core-01](https://transfer.sh/Gs5d9/diags-20150123-005959.tar.gz)
[core-02](https://transfer.sh/hT1vb/diags-20150123-005919.tar.gz)

**Comment by Lukasa** [comment]
This error occurs when the Felix that is supposed to set the interface up does not respond within 10 seconds. In a 'real' system this will be handled by the plugin, but in this early demonstration version the plugin treats it as a severe error and exits.

Looking at the logs, the relevant Felix is the one on core-01. That Felix starts processing the message at 00:55:22,418, more than one second after the message was sent (which is an indication of a fairly slow system). Felix then goes through the motions of programming the interface and simply stops, finally sending the response at 00:55:49,466, more than 27 seconds after it started processing it.

The big gap occurs in this log sequence:

```
2015-01-23 00:55:23,077 [DEBUG] calico.felix.futils 81: Calling out to system : ['ipset', 'list', 'felix-6-from-icmp-fde2b11495d']
2015-01-23 00:55:48,186 [DEBUG] calico.felix.endpoint 225: ACLs for fde2b11495d are {u'v4': {u'inbound': [{u'protocol': None, u'cidr': u'192.168.1.1/32', u'group': None, u'port': None}], u'outbound': [{u'protocol': None, u'cidr': u'192.168.1.1/32', u'group': None, u'port': None}, {u'protocol': None, u'cidr': u'0.0.0.0/0', u'group': None, u'port': None}], u'inbound_default': u'deny', u'outbound_default': u'deny'}, u'v6': {u'inbound': [], u'outbound': [], u'inbound_default': u'deny', u'outbound_default': u'deny'}}
```

The reason for the gap is that there is a large section of unlogged code (bug number one) corresponding to programming the ACLs (namely the function `set_ep_specific_rules`). This *can* be quite slow when running on underpowered VMs, as it does quite a lot of heavy lifting to handle putting rules into the kernel.

In the very short term I'm afraid the only solution I can advise is to increase the CPU power of the VM. In particular, having more than one virtual core would be advantageous: Felix getting pre-empted by another thread will cause real problems.

In the longer term, Felix needs to be able to respond to ENDPOINTCREATED messages faster, as well as to avoid getting blocked on programming those interfaces. Happily, we were already planning to look into Felix scaling: this is a good issue to prioritise this.

@plwhite, does this diagnosis seem correct to you?

**Comment by Lukasa** [comment]
Tracking these issues as metaswitch/calico#141, metaswitch/calico#142, and metaswitch/calico#143.

**Comment by plwhite** [comment]
That all sounds right. It's not 100% clear if there's a pragmatic short term fix for this (e.g. pushing up timeouts), but in practice I think running in containers within VMs within VMs is really just getting to the point where it's not surprising we hit issues.

**Comment by spikecurtis** [comment]
Closing, `calico-docker` is no longer on the affected branch of Felix.
