### ISSUE TITLE
Calicoctl rule json command fails with TypeError: IPNetwork('192.168.0.1/32') is not JSON serializable

### ISSUE THREAD

**Issue by matthewdupre** [Metaswitch/calico-docker#317]
I created one rule with calicoctl (on top of the defaults), but when I tried to view the json for them with `calicoctl profile PROFILE1 rule json` I got the following traceback.

```
root@calico03:~# calicoctl profile PROFILE1 rule show
Inbound rules:
   1 allow from tag PROFILE1
   2 allow udp from 192.168.0.1/32 to tag PROFILE1
Outbound rules:
   1 allow

root@calico03:~# etcdctl get /calico/v1/policy/profile/PROFILE1/rules
{"id": "PROFILE1", "inbound_rules": [{"action": "allow", "src_tag": "PROFILE1"}, {"action": "allow", "dst_tag": "PROFILE1", "protocol": "udp", "src_net": "192.168.0.1/32"}], "outbound_rules": [{"action": "allow"}]}

root@calico03:~# calicoctl profile PROFILE1 rule json
{
  "id": "PROFILE1",
  "inbound_rules": [
    {
      "action": "allow",
      "src_tag": "PROFILE1"
    },
    {
      "action": "allow",
      "dst_tag": "PROFILE1",
      "protocol": "udp",
      "src_net": Unexpected error executing command.

Traceback (most recent call last):
  File "<string>", line 1817, in <module>
  File "<string>", line 721, in profile_rule_show
  File "/code/build/calicoctl/out00-PYZ.pyz/json", line 189, in dump
  File "/code/build/calicoctl/out00-PYZ.pyz/json.encoder", line 434, in _iterencode
  File "/code/build/calicoctl/out00-PYZ.pyz/json.encoder", line 408, in _iterencode_dict
  File "/code/build/calicoctl/out00-PYZ.pyz/json.encoder", line 332, in _iterencode_list
  File "/code/build/calicoctl/out00-PYZ.pyz/json.encoder", line 408, in _iterencode_dict
  File "/code/build/calicoctl/out00-PYZ.pyz/json.encoder", line 442, in _iterencode
  File "/code/build/calicoctl/out00-PYZ.pyz/json.encoder", line 184, in default
TypeError: IPNetwork('192.168.0.1/32') is not JSON serializable
```

**Comment by robbrockbank** [comment]
@matthewdupre Do you know what version of the calicoctl tool you are using - I believe this issue has been fixed in one of the recent releases.

**Comment by matthewdupre** [comment]
I think I installed it on the the 3rd, so a week and a half ago.  Is there an easy way to get the version of the tool?  (If not there should be!)

**Comment by TrimBiggs** [comment]
That's a good point.  We should have a 'version' command that simply prints the version number.

**Comment by robbrockbank** [comment]
See issue #268

**Comment by TrimBiggs** [comment]
Yup, this is working fine on the master branch.
