### ISSUE TITLE
Stacktrace when running calicoctl node without sudo

### ISSUE THREAD

**Issue by tomdee** [Metaswitch/calico-docker#394]
Unexpected error executing command.

Traceback (most recent call last):
  File "<string>", line 92, in <module>
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 168, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/calico_ctl.node", line 187, in node_start
  File "/code/build/calicoctl/out00-PYZ.pyz/os", line 157, in makedirs
OSError: [Errno 13] Permission denied: '/var/log/calico'

**Comment by tomdee** [comment]
Hit this on CoreOS (on GCE) running v0.5.3

**Comment by robbrockbank** [comment]
Fixed by #395
