### ISSUE TITLE
"No such image" when running calicoctl node

### ISSUE THREAD

**Issue by Symmetric** [Metaswitch/calico-docker#56]
Running the `calicoctl node` command, I got the following error:

```
(calico-docker)paul@ubuntu:~/git/calico-docker$ sudo ~/.virtualenvs/calico-docker/bin/python calicoctl.py node --ip=1.2.3.4
('Connecting to Etcd server %s', '127.0.0.1:4001')
Traceback (most recent call last):
  File "calicoctl.py", line 793, in <module>
    ip6=ip6)
  File "calicoctl.py", line 385, in node
    "/var/log/calico"])
  File "/home/paul/.virtualenvs/calico-docker/local/lib/python2.7/site-packages/docker/client.py", line 546, in create_container
    return self.create_container_from_config(config, name)
  File "/home/paul/.virtualenvs/calico-docker/local/lib/python2.7/site-packages/docker/client.py", line 554, in create_container_from_config
    return self._result(res, True)
  File "/home/paul/.virtualenvs/calico-docker/local/lib/python2.7/site-packages/docker/client.py", line 98, in _result
    self._raise_for_status(response)
  File "/home/paul/.virtualenvs/calico-docker/local/lib/python2.7/site-packages/docker/client.py", line 94, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 404 Client Error: Not Found ("No such image: calico/node:latest (tag: latest)")
```

This looked a bit suspicious, so I tried pulling the image manually -- doing that allowed `calicoctl node` to function properly:

```
(calico-docker)paul@ubuntu:~/git/calico-docker$ docker run calico/node:latest
Unable to find image 'calico/node:latest' locally
Pulling repository calico/node
...
Status: Downloaded newer image for calico/node:latest
*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/rc.local...
flag needs an argument: -node
...
(calico-docker)paul@ubuntu:~/git/calico-docker$ sudo ~/.virtualenvs/calico-docker/bin/python calicoctl.py node --ip=1.2.3.4
('Connecting to Etcd server %s', '127.0.0.1:4001')
Docker Remote API is on port 2377.  Run 

export DOCKER_HOST=localhost:2377

before using `docker run` for Calico networking.

Calico node is running with id: 56bf2205c4be133049cf39c6044d7c75ea231cbc35eb1b133fba511982bbeb69
```

I think we need to call /images/create first to pull the image. (c.f. docker run description, ss [3.1](https://docs.docker.com/reference/api/docker_remote_api_v1.17/))

**Comment by spikecurtis** [comment]
Fixed in master.
