### ISSUE TITLE
calicoctl node fails on Ubuntu with Docker 1.12

### ISSUE THREAD

**Issue by spikecurtis** [Metaswitch/calico-docker#75]
`apt-get install docker.io` apparently installs Docker 1.12, which causes an API error when we run `calicoctl node`.

```
root@999ab68d:~# ./calicoctl node --ip=147.75.192.191 --ip6=2604:1380::bf --node-image=calico/node:latest
Pulling Docker image calico/node:latest
Traceback (most recent call last):
  File "<string>", line 820, in <module>
  File "<string>", line 386, in node
  File "<string>", line 429, in _find_or_pull_node_image
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 777, in pull
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 123, in _result
  File "/code/build/calicoctl/out00-PYZ.pyz/docker.client", line 119, in _raise_for_status
docker.errors.APIError: 404 Client Error: Not Found ("client and server don't have same version (client : 1.16, server: 1.12)")
```

We should investigate whether we can be compatible with this version of the API, and if so, use it.

**Comment by tomdee** [comment]
We're using features that require at least API version 1.15. Closing this as wontfix 
````
  File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 454, in create_container
    'host_config is not supported in API < 1.15'
docker.errors.InvalidVersion: host_config is not supported in API < 1.15
````
