### ISSUE TITLE
calicoctl doesn't give clean error messages.

### ISSUE THREAD

**Issue by alexaltair** [Metaswitch/calico-docker#96]
While trying out the calico-docker demo, I got the following stack traces from the calicoctl executable.
```
core@core-01 ~ $ sudo ./calicoctl node --ip=172.17.8.101    
Traceback (most recent call last):
  File "<string>", line 820, in <module>
  File "<string>", line 286, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/node.adapter.datastore", line 303, in add_ip_pool
  File "/code/build/calicoctl/out00-PYZ.pyz/etcd.client", line 269, in write
  File "/code/build/calicoctl/out00-PYZ.pyz/etcd.client", line 582, in api_execute
  File "/code/build/calicoctl/out00-PYZ.pyz/etcd.client", line 600, in _handle_server_response
etcd.EtcdException: raft.Server: Not current leader
```
```
core@core-01 ~ $ sudo ./calicoctl node --ip=172.17.8.101    
Traceback (most recent call last):
  File "<string>", line 820, in <module>
  File "<string>", line 286, in node
  File "/code/build/calicoctl/out00-PYZ.pyz/node.adapter.datastore", line 303, in add_ip_pool
  File "/code/build/calicoctl/out00-PYZ.pyz/etcd.client", line 269, in write
  File "/code/build/calicoctl/out00-PYZ.pyz/etcd.client", line 582, in api_execute
  File "/code/build/calicoctl/out00-PYZ.pyz/etcd.client", line 600, in _handle_server_response
etcd.EtcdException: raft.Server: Not current leader
```
This was useful for me, but it's probably not what we want our users seeing. Should we write generally cleaner-looking error messages?

**Comment by robbrockbank** [comment]
Fixed in pull request #113, pending review.

Fix handles:
-  etcd errors (prints generic is etcd running message)
-  prints error if container not in calico network with details of why and how to fix
-  prints error if docker command needs sudo access

**Comment by robbrockbank** [comment]
Merged in changes from #113.

Closing issue.

**Comment by alexaltair** [comment]
Another example;

```bash
$ sudo calicoctl reset
Removing all data from data store
$ sudo calicoctl pool add 192.168.0.0/16
$ sudo calicoctl container add container1 192.168.1.4
Traceback (most recent call last):
  File "<string>", line 1130, in <module>
  File "<string>", line 185, in container_add
  File "/code/build/calicoctl/out00-PYZ.pyz/node.adapter.datastore", line 736, in get_default_next_hops
KeyError: 'BIRD configuration for host <hostname> not found.'
```

**Comment by tomdee** [comment]
@robbrockbank Is this one you can take a look at?

**Comment by robbrockbank** [comment]
Another example
```
+ dist/calicoctl pool add 127.a.0.1
Traceback (most recent call last):
  File "<string>", line 1109, in <module>
  File "<string>", line 1012, in validate_arguments
  File "/code/build/calicoctl/out00-PYZ.pyz/netaddr.ip", line 907, in __init__
  File "/code/build/calicoctl/out00-PYZ.pyz/netaddr.ip", line 774, in parse_ip_network
  File "/code/build/calicoctl/out00-PYZ.pyz/netaddr.strategy.ipv4", line 277, in expand_partial_address
ValueError: invalid literal for int() with base 10: 'a'
+ dist/calicoctl pool add aa:bb::zz
```

**Comment by tomdee** [comment]
And another - note the error is OK, but it never returns.

```
sudo ./calicoctl.py node --ip=10.0.2.15
Error accessing etcd (No more machines in the cluster).  Is etcd running?




^C

^C^C^C


^C^C



```

**Comment by alexaltair** [comment]
Fixed in libnetwork-rebased.
