### ISSUE TITLE
docker run will get stuck if command exit immediately

### ISSUE THREAD

**Issue by frostynova** [Metaswitch/calico-docker#99]
```
export DOCKER_HOST=localhost:2377
docker run -e CALICO_IP=auto ubuntu date
```

Then it will hang. Powerstrip error log is:

```
2015-04-29 07:58:19,634 [ERROR] powerstrip-calico.py.__main__ 91: Failed to process POST
Traceback (most recent call last):
  File "powerstrip-calico.py", line 83, in render_POST
    result = self._handle_post_hook(request, request_content)
  File "powerstrip-calico.py", line 112, in _handle_post_hook
    self._install_endpoint(client_request)
  File "powerstrip-calico.py", line 174, in _install_endpoint
    next_hop_ips=next_hop_ips)
  File "/adapter/netns.py", line 122, in set_up_endpoint
    check_call("ip link set %s netns %s" % (iface_tmp, cpid), shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ip link set tmp7ff46598ee4 netns 18258' returned non-zero exit status 2
```

I think this is because powerstrip has no time to execute the POST-HOOK which added ip for the container.

If i add a ```sleep 3``` then everything is ok.
```
docker run -e CALICO_IP=auto ubuntu bash -c "sleep3; date"
````

But i think it would be better if not get stuck in this case.

**Comment by robbrockbank** [comment]
Fix for issue #95 added protective exception handling in the webhooks - so this no longer hangs.

You will still see the exception in the logs, but the docker command completes.
